name: Symfony CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
          tools: composer, phpstan, phpunit

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --dev

      - name: Install PHP-CS-Fixer
        run: composer require --dev friendsofphp/php-cs-fixer

      - name: Debug Composer Packages
        run: ls -la vendor/bin

      - name: Run PHP-CS-Fixer
        run: |
          if [ -f vendor/bin/php-cs-fixer ]; then
            vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no .
          else
            echo "php-cs-fixer not found, installing globally..."
            composer global require friendsofphp/php-cs-fixer
            $(composer global config home)/vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no .
          fi

      - name: Run PHP lint
        run: find src tests -name "*.php" -exec php -l {} \;

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Audit de sécurité
        run: composer audit --format=json --no-interaction
        continue-on-error: true
      
      - name: Dump environment variables for production
        run: composer dump-env prod
        env:
          APP_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
